- Kindred
  - Breggle
    - Description: Proud goatfolk whose horn length determines their social standing.
  - Elf
    - Description: Wanderers from Fairy, wielders of innate fairy glamours.
  - Grimalkin
    - Description: Shape-shifting cat fairies.
  - Human
    - Description: 
  - Mossling
    - Description: Gnarled, woody humanoids whose fertile flesh hosts mosses, moulds, and fungi.
  - Woodgrue
    - Description: Bat-faced goblins with a penchant for music and arson.

- Ability Scores
  - Strength
  - Intelligence
  - Wisdom
  - Dexterity
  - Constitution
  - Charisma

- Classes
  - Cleric
  - Enchanter
  - Fighter
  - Friar
  - Hunter
  - Knight
  - Magician
  - Minstrel
  - Thief

